### PR TITLE
Fix: rename doc_fragment to doc_fragments

### PR DESCRIPTION
**Pull request by mnecas**
##### SUMMARY

Hi,
there was the wrong name of the folder. 
https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#using-documentation-fragments-in-collections

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

doc_fragments
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mnecas** [comment]
@modular-magician @rambleraptor

**Comment by AlanCoding** [comment]
I don't see where this was ever used

https://github.com/ansible-collections/ansible_collections_google/search?q=extends_documentation_fragment&unscoped_q=extends_documentation_fragment

Could the use be from this?

https://github.com/ansible-collections/community.general/blob/b635c363486168545a69c5042764c2f2a2c2a142/plugins/lookup/gcp_storage_file.py#L26-L27

that points here:

https://github.com/ansible-collections/community.general/blob/b635c363486168545a69c5042764c2f2a2c2a142/plugins/doc_fragments/gcp.py

So it looks like something landed messy. Need to determine if this collection intends to adopt that lookup plugin. Even so, why would there be a doc fragment that only 1 plugin used??

Since this split so early, and doc_fragments were converted to plugins later, I wonder if it didn't work when this originated, so they duplicated the doc fragments.

**Comment by rambleraptor** [comment]
I can answer this! When I migrated the collection over, doc_fragments weren't yet built into collections. I was told that it wasn't a huge priority at the time.

I ended up putting all of the information from the doc fragment directly into the modules. I must've forgotten to delete the fragment itself.

**Comment by AlanCoding** [comment]
Then I don't think this PR is what you want. The folder should be deleted instead, and if someone wanted to refactor the DOCUMENTATION strings, they could do it anew.

The other question is whether `plugins/lookup/gcp_storage_file.py` should be adopted here. This sort of thing has happened with other collections. It's bizarre to find that at `community.general.gcp_storage_file`.

**Comment by mnecas** [comment]
I'm not a maintainer of this collection, just noticed that it had the wrong name, if you want I can drop the pr or remove the folder, it's up to you.

**Pull request merged**
